name: TopPlayers
main: Fayu\TopPlayers
version: 1.0.0
api: [4.0.0]
author: Xx2Fayuth2xX

commands:
  top:
    default: op
    description: spawn floating text TOP
    permission: top.create
permissions:
  top:
    default: op
    chidlren:
      stp.use:
        default: op
